version: '{build}'
build:
  project: Peasy.sln
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
  - nuget restore Peasy.sln
install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe
nuget:
  disable_publish_on_pr: true
test: on
